name: dev-deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Verify dist Directory
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory does not exist"
            exit 1
          fi

      - name: Copy build to server
        run: |
          scp -i ${{ secrets.DEPLOY_PRIVATE_KEY }} -r dist/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/home/kaliwahab/chatapp/
        
      - name: Verify temporary directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            echo "Listing contents of /home/kaliwahab/chatapp:"
            ls -l /home/kaliwahab/chatapp || { echo "Failed to list /home/kaliwahab/chatapp"; exit 1; }
            echo "Listing contents of /usr/share/apis/chatapp:"
            ls -l /usr/share/apis/chatapp || { echo "Failed to list /usr/share/apis/chatapp"; exit 1; }

      - name: Finalize Deployment (Move and Clean)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            # Ensure the target directory exists
            sudo mkdir -p /usr/share/apis/chatapp
            # Ensure proper permissions
            sudo chown ${{ secrets.DEPLOY_USER }} /usr/share/apis/chatapp
            # Clean up old files
            sudo rm -rf /usr/share/apis/chatapp/*
            # Move new files
            sudo mv /home/kaliwahab/chatapp/* /usr/share/apis/chatapp/
            # Remove temporary files
            sudo rm -rf /home/kaliwahab/chatapp
            echo "Deployment finished."
