name: dev-deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Compress Project Files
        run: |
          tar -czf app.tar.gz *

      - name: Clear previous build on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            mkdir ~/chatapp
            sudo rm -rf ~/usr/share/apis/chatapp/*

      - name: Copy Project Files to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          source: "app.tar.gz"
          target: ~/chatapp

      - name: Finalize Deployment via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd ~/chatapp
            tar -xzf app.tar.gz
            rm app.tar.gz
            cat << 'EOF' > .env
            ${{ secrets.ENVIRONMENT }}
            EOF
            pnpm i && pnpm build 
            cd ..
            sudo mv ~/chatapp /usr/share/apis/
            echo "Deployment finished."
