name: dev-deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Compress build
        run: tar -czf dist.tar.gz dist

      - name: Copy build to server
        run: |
          scp -i ${{ secrets.DEPLOY_PRIVATE_KEY }} -v dist.tar.gz ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:~/chatapp/

      - name: Finalize Deployment via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd ~/chatapp
            tar -xzf dist.tar.gz
            sudo mkdir -p /usr/share/apis/chatapp
            sudo rm -rf /usr/share/apis/chatapp/*
            sudo mv dist/* /usr/share/apis/chatapp/
            sudo rm -rf dist.tar.gz
            echo "Deployment finished."
