name: dev-deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Compress build
        run: tar -czf dist.tar.gz dist

      - name: Upload build to server
        run: |
          scp -i ${{ secrets.DEPLOY_PRIVATE_KEY }} dist.tar.gz ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/home/kaliwahab/

      - name: Verify temporary directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            echo "Listing contents of /home/kaliwahab/chatapp:"
            ls -l /home/kaliwahab

      - name: Finalize Deployment via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            # Extract build
            cd /home/kaliwahab
            tar -xzf dist.tar.gz
            # Ensure the target directory exists
            sudo mkdir -p /usr/share/apis/chatapp
            # Clean up old files
            sudo rm -rf /usr/share/apis/chatapp/*
            # Move new files
            sudo mv dist/* /usr/share/apis/chatapp/
            # Clean up temporary files
            sudo rm -rf /home/kaliwahab/dist.tar.gz
            echo "Deployment finished."
