name: dev-deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Verify dist Directory
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory does not exist"
            exit 1
          fi

      - name: Sync build to server (Temporary Directory)
        run: |
          rsync -avz --delete dist/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/home/kaliwahab/chatapp
        env:
          RSYNC_RSH: "ssh -i ${{ secrets.DEPLOY_PRIVATE_KEY }}"

      - name: Finalize Deployment (Move and Clean)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            sudo rm -rf /usr/share/apis/chatapp/*
            sudo mv /home/kaliwahab/chatapp/* /usr/share/apis/chatapp/
            sudo rm -rf /home/kaliwahab/chatapp

