name: dev-deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Compress Build and Dependencies
        run: |
          tar -czf app.tar.gz dist
          tar -czf node_modules.tar.gz node_modules 

      - name: Create Temp Build Folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            mkdir -p ~/chatapp

      - name: Copy Packages Files Build to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          source: "package.json"
          target: ~/chatapp

      - name: Copy Node Modules Folder Build to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          source: "node_modules.tar.gz"
          target: ~/chatapp

      - name: Copy Dist to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          source: "app.tar.gz"
          target: ~/chatapp

      - name: Finalize Deployment via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd ~/chatapp
            tar -xzf app.tar.gz
            tar -xzf node_modules.tar.gz
            sudo mkdir -p /usr/share/apis/chatapp
            sudo rm -rf /usr/share/apis/chatapp/*
            sudo mv dist/ /usr/share/apis/chatapp/
            sudo mv node_modules /usr/share/apis/chatapp/
            sudo mv package.json /usr/share/apis/chatapp/
            sudo rm -rf app.tar.gz
            sudo rm -rf node_modules.tar.gz
            sudo rm -rf package.json
            echo "Deployment finished."
            rm -rf ~/chatapp
